### PR TITLE
Dom updates hk

### LINKED ISSUE #39: Testing with Spies: set up files
- test DOM manipulation

### LINKED ISSUE #116: Favorites Button is Broken

### LINKED ISSUE #117: Favorite button broken

### LINKED ISSUE #120: Refactor: use domUpdates object to call methods that update the DOM on load

### PR DESCRIPTION
**Pull request by hannakim91**
### What’s this PR do?  
- Create `domUpdates` object and transplant functions in `scripts.js` that involve populating UI on load to be methods of `domUpdates`. Connect those functions to take in data fetched from API as properties of `domUpdates` and update any variables / helper function calls to it. 
- Refactor any functions left in `scripts.js` that take in functions moved into `domUpdates` as methods to call those methods.
- Cleaned up syntax issues in `pantry.js` and `fetches.js`
- Test DOM update using Chai/Spies

### Where should the reviewer start?  
- domUpdate.js / domUpdate-test.js
- scripts.js
- fetches.js / pantry.js
### Any background context you want to provide?  
Clean up `scripts.js` by moving and organizing functions to be called in `domUpdates` 
### What are the relevant tickets?  
Resolves #39 
Resolves #117
Resolves #116
Resolves #120
### Questions: 
- Think it'd be a good idea to at least run eslint / clean up commented out code from all our different files.

### CODE REVIEW

File: src/domUpdates.js [hunk 1]
```diff
@@ -0,0 +1,185 @@
+const domUpdates = {
```
Comment (npdarrington) [inline src/domUpdates.js:1]: This is an interesting and clean way that make sure that everything is separated and easy to find when troubleshooting! Let's make sure that we can change some of these default functions and start adding in our own class methods.

File: src/domUpdates.js [hunk 2]
```diff
@@ -0,0 +1,185 @@
...
+      tagList.insertAdjacentHTML("beforeend", tagHtml);
+    });
+  }
+
+
+}
+
+export default domUpdates;
+
+//anything that populates DOM
```
Comment (JWoltjen) [inline src/domUpdates.js:179]: We should remove this pseudo code when we're finished with the final product.

File: src/domUpdates.js (hunk 1 above)
Comment (aemcdonald) [inline src/domUpdates.js:1]: Excellent job creating the DOM updates object & assigning the properties to null, then reassigning them later. This takes care of all the undefined errors we were getting initially. Overall domUpdates looks clean, organized & like everything is hooked up properly.

File: src/scripts.js [hunk 3]
```diff
@@ -36,111 +35,118 @@ searchBtn.addEventListener("click", searchRecipes);
...
-let recipe;
 let user;
-let pantry;
 let ingredientsData;
-let users;
+let recipeData;
+let recipe;
+let recipes = []
+let pantry;
+let users; //do we need this still?
```
Comment (npdarrington) [inline src/scripts.js:44]: It seems like some of these are unnecessary and can be confusing on which one is actually used. Anything that is being repeated between domUpdates.js and scripts.js let's test whether they are actually needed or not for functionality and remove them if they are not needed.

File: test/domUpdates-test.js [hunk 4]
```diff
@@ -0,0 +1,28 @@
+const chai = require('chai');
+const expect = chai.expect;
+const spies = require('chai-spies');
+import domUpdates from '../src/domUpdates';
+// import Recipe from '../src/recipe';
+import data from '../src/data/recipe-data';
+
+chai.use(spies)
+
+describe ('DOM Test', () => {
```
Comment (JWoltjen) [inline test/domUpdates-test.js:10]: Way to go above and beyond testing a domupdating method!!

**Review by JWoltjen — APPROVED** [review]
Great work driving yesterday, Hannah!

File: test/domUpdates-test.js [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+
+  
+  beforeEach(() => {
```
Comment (aemcdonald) [inline test/domUpdates-test.js:13]: Great job getting the testing with chai spies started.

**Review by aemcdonald — APPROVED** [review]
While I would love to have more time to add more robust testing using chai spies, I think in the interest of time & our pending due date we should focus on getting our POSTs all hooked up & functioning properly

File: src/scripts.js [hunk 6]
```diff
@@ -337,42 +344,42 @@ function toggleMenu() {
...
-    let ingredientHtml = `<li><input type="checkbox" class="pantry-checkbox" id="${ingredient.id}">
-      <label for="${ingredient.name}">${ingredient.name}, ${ingredient.count}</label></li>`;
-    document.querySelector(".pantry-list").insertAdjacentHTML("beforeend",
-      ingredientHtml);
-  });
-}
+// function findPantryInfo() {
+//   user.pantry.forEach(item => {
+//     let itemInfo = ingredientsData.find(ingredient => {
+//       return ingredient.id === item.ingredient;
```
Comment (npdarrington) [inline src/scripts.js:358]: A lot of our PR's contain comments. Let's make sure that in our PR's, we are only pushing comments that are needed instead of large blocks of code that the functionality has already been tested out of and confirmed working.

**Review by npdarrington — APPROVED** [review]
