### PR TITLE
Nd pantry refactor

### LINKED ISSUE #69: Refactor: Recipe.calculateIngredientsCost()
Recipe.calculateIngredientsCost can be broken down into some helper methods: like getting the recipeIngredients corrresponding item in ingredientData array is a helper function that gets called into the main method

### LINKED ISSUE #71: Refactor: Pantry.getRecipeIngredientsInStock() / Pantry.getMissingIngredients()
Can these two be refactored/merged into a shorter function?
Any addtl testing possible?

### LINKED ISSUE #75: Refactor: Pantry doesn't need a userPantry property
delete from constructor

### PR DESCRIPTION
**Pull request by npdarrington**
What’s this PR do?  
- This PR refactors the Pantry class and the `getRecipeIngredientsInStock()` and `getMissingIngredientsPrice()` methods.
- This PR refactors for linting consistency.
- This PR refactors the necessary test files reflecting the new changes in `recipe-test.js` and `pantry-test.js`.

Where should the reviewer start?  
- Pull the newest updates in this branch.

How should this be manually tested?  
- Open `recipe-test.js`, `pantry-test.js`, `recipe.js` and `pantry.js`.
- run `npm test` to ensure all tests are still passing.
- check the context of the code to ensure efficiency and developer empathy.

Any background context you want to provide?  
- N/A

What are the relevant tickets?  
Closes #69 
Closes #71 
Closes #75 

Screenshots (if appropriate)  
- N/A

Questions: 
- N/A

### CODE REVIEW

File: src/Pantry.js [hunk 1]
```diff
@@ -1,99 +1,41 @@
...
 
-  getMissingIngredients(user, recipeIngredients) {
-    const stockedItems = this.getRecipeIngredientsInStock(user, recipeIngredients);
-    const missingIngredients = recipeIngredients.reduce((missingIngred, ingredient) => {
-      let ingredientNotFound = stockedItems.find(item => {
-        return +item['ingredient'] === ingredient.id;
-      })
-      if (!ingredientNotFound) {
-        missingIngred.push(ingredient)
+  getRecipeIngredientsInStock(user, recipe) {
```
Comment (hannakim91) [inline src/Pantry.js:9]: New method looks great! A lot more straight forward than having 2 methods previously that went back and forth between the datasets

**Review by hannakim91 — APPROVED** [review]

File: src/Pantry.js [hunk 2]
```diff
@@ -1,99 +1,41 @@
...
+    return recipe.ingredients.reduce((ingredientsMissing, ingredientForRecipe) => {
+      let pantryInventory = this.getPantryItems(user);
+      let item = pantryInventory.find(item => {
+        return ingredientForRecipe.id === item.ingredient;
+      });
+      if (!item || ingredientForRecipe.quantity.amount > item.amount) {
+        let amountInPantry = (item && item.amount) || 0;
```
Comment (aemcdonald) [inline src/Pantry.js:16]: I really like how you chose to refactor here. Using the || operator to assign the amount to 0 if undefined is returned is a great way to consolidate our previous code.

**Review by JWoltjen — APPROVED** [review]
Well done on this elegant refactor

**Review by aemcdonald — APPROVED** [review]
